[package]
name = "makair-telemetry"
version = "1.1.0"
authors = ["David Sferruzza <david.sferruzza@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
crc32fast = "1.2.0"
log = "0.4.11"
nom = "5.1.2"
rand = "0.7.3"
serial = "0.4.0"
clap = { version = "3.0.0-beta.2", optional = true }
env_logger = { version = "0.7.1", optional = true }

[dev-dependencies]
proptest = "0.10.1"

[lib]
name = "telemetry"
path = "src/lib.rs"

[features]
build-binary = ["clap", "env_logger"]

[[bin]]
name = "makair_telemetry"
path = "src/bin.rs"
required-features = ["build-binary"]
