[package]
name = "makair-telemetry"
version = "1.2.5"
authors = ["David Sferruzza <david.sferruzza@gmail.com>", "Valerian Saliou <valerian@valeriansaliou.name>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
crc32fast = "1.2.0"
log = "0.4.11"
nom = "6.0.0"
rand = "0.7.3"
serial = "0.4.0"
clap = { version = "3.0.0-beta.2", optional = true }
env_logger = { version = "0.8.1", optional = true }
serde = { version = "1.0.117", features = ["derive"], optional = true }
serde_json = { version = "1.0.59", optional = true }

[dev-dependencies]
proptest = "0.10.1"

[lib]
name = "telemetry"
path = "src/lib.rs"

[features]
build-binary = ["clap", "env_logger", "serde_json", "serialize-messages"]
serialize-messages = ["serde"]

[[bin]]
name = "makair_telemetry"
path = "src/cli/bin.rs"
required-features = ["build-binary"]
