name: Telemetry All

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install latest stable
        uses: actions-rs/toolchain@v1.0.6
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-check

      - name: Lint
        uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets --all-features -- -D warnings

      - name: Check code style
        uses: actions-rs/cargo@v1.0.1
        with:
          command: fmt
          args: --all -- --check

      - name: Build lib
        uses: actions-rs/cargo@v1.0.1
        with:
          command: build
          args: --all-targets --all-features

      - name: Test lib
        uses: actions-rs/cargo@v1.0.1
        with:
          command: test
          args: --all-targets --all-features

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install latest stable
        uses: actions-rs/toolchain@v1.0.6
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-build

      - name: Build debug tool
        uses: actions-rs/cargo@v1.0.1
        with:
          command: build
          args: --bin makair_telemetry_cli --features=build-binary --release

      - name: Archive binary
        uses: actions/upload-artifact@v1
        with:
          name: makair_telemetry_cli
          path: target/release/makair_telemetry_cli

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install latest stable
        uses: actions-rs/toolchain@v1.0.6
        with:
            toolchain: nightly
            override: true

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-docs

      - name: Build documentation
        uses: actions-rs/cargo@v1.0.1
        with:
          command: doc
          args: --all-features
        env:
          RUSTDOCFLAGS: --cfg doc_cfg

      - name: Prepare documentation to be hosted
        run: |
          cp .github/documentation_index.html target/doc/index.html
          tar czvf doc.tar.gz target/doc/

      - name: Archive documentation
        uses: actions/upload-artifact@v1
        with:
          name: doc
          path: doc.tar.gz

      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@releases/v3
        if: github.ref == 'refs/heads/master'
        with:
          BRANCH: gh-pages
          FOLDER: target/doc/
          TARGET_FOLDER: ./
